resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 3s
    instances:
      products:
        base-config: defecto

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://127.0.0.1:9000
          issuer-uri: ${IP_ADDR:http://127.0.0.1:9000}
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
#            issuer-uri: http://127.0.0.1:9000
            issuer-uri: ${IP_ADDR:http://127.0.0.1:9000}
  cloud:
    gateway:
      routes:
        - id: oauth-server
          uri: lb://msvc-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: msvc-cliente
          uri: lb://msvc-cliente
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=2
        - id: msvc-user
          uri: lb://msvc-user
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
#        - id: msvc-product
#          uri: lb://msvc-product
#          predicates:
#            - Path=/api/products/**
          # - Header=token, \d+
          # - Method=GET, POST
          # - Query=color
          # - Cookie=color, azul
          # - Header=Content-Type, application/json
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: products
#                statusCodes: 500
#                fallbackUri: forward:/api/items/5
#            - StripPrefix=2
#        - id: msvc-item
#          uri: lb://msvc-item
#          predicates:
#            - Path=/api/items/**
#          filters:
#            - StripPrefix=2
            #- AddRequestHeader=token-request, aabbsjdfjsaj
            #- AddResponseHeader=token-response, 234340823
            #- AddRequestParameter=name, Andres
            #- SetResponseHeader=Content-Type, text/plain
#        - id: msvc-order
#          uri: lb://msvc-order
#          predicates:
#            - Path=/api/orders/**
#          filters:
#            - StripPrefix=2